baseurl = "http://dreamland.blackcedar.co.nz"
languageCode = "en-nz"
title = "Dreamland wth Brunch"

# SectionPages creates an automagic menu
#SectionPagesMenu = "main"

showChildren = true

# All of the top level pages are defined directly in the page frontmatter


[menu]

  [[menu.main]]
  name       = "Pages"
  url        = "/video-tour/"
  weight = 15

  [[menu.main]]
  name       = "Homepage One"
  url        = "/index-1/"
  parent     = "Home"

  [[menu.main]]
  name       = "Homepage Two"
  url        = "/index-2/"
  parent     = "Home"

  [[menu.main]]
  name       = "One page Style"
  url        = "/index-3/"
  parent     = "Home"



  [[menu.main]]
  identifier = "gallery"
  name       = "Gallery"
  url        = "/gallery/"
  parent     = "Pages"
  weight = 1

  [[menu.main]]
  name       = "Video Tour"
  identifier   = "video-tour-menu-item"
  url        = "/video-tour/"
  parent     = "Pages"
  weight = 2

  [[menu.main]]
  name       = "Sidebar Page"
  url        = "/blog-two-column/"
  parent     = "Pages"
  weight = 3

  [[menu.main]]
  name       = "Left Sidebar"
  url        = "/blog-leftbar/"
  parent     = "Sidebar Page"
  weight = 1

  [[menu.main]]
  name       = "Right Sidebar"
  url        = "/blog/"
  parent     = "Sidebar Page"
  weight = 2

  [[menu.main]]
  name       = "Blog Details"
  url        = "/blog-detail/"
  parent     = "Sidebar Page"
  weight = 3


  [[menu.main]]
  name       = "Blog Normal"
  url        = "/blog/"
  parent     = "Blog"
  weight = 1

  [[menu.main]]
  name       = "Blog Two Column"
  url        = "/blog-two-column/"
  parent     = "Blog"
  weight = 2

  [[menu.main]]
  name       = "Blog Details"
  url        = "/blog-detail/"
  parent     = "Blog"
  weight = 3

  [[menu.main]]
  name       = "Gallery Full Width"
  url        = "/gallery/"
  parent     = "Gallery"
  weight = 1

  [[menu.main]]
  name       = "Gallery Boxed"
  url        = "/gallery-2/"
  parent     = "Gallery"
  weight = 2
